### ISSUE TITLE
Reboot issue with V9.0.17

### ISSUE THREAD

**Issue by 19201003080114** [GeekMagicClock/smalltv-ultra#15] opened 2024-03-26 22:25 UTC
After updating to V9.0.17, now I have reboot issues that I didn't have before when I had V9.0.15

Note: I have my own weather API key so my update interval is every 5 mins

I know it rebooted because:

- Forecast screen is blank with no data. Then I know it rebooted within the last 5 mins.

- Randomly I see display showing GIFTV asking to connect 192.168.4.1. I know this could happen if power is cut 3 times while booting up, or when it cannot connect to wifi. But my wifi is OK (Router didn't reboot, or did not lose connection), and USB-C cable has not been touched or changed as when I was using V9.0.15.

Disappointing but I will downgrade back to V9.0.15. Forecast screen is broken but it is not as bad as random reboots.

**Comment by GeekMagicClock** [comment] 2024-03-27 01:07
Thank you for the report, I'll try your steps to confirm the problem.

**Comment by GeekMagicClock** [comment] 2024-03-27 01:40
Hi, what is your location? I have try set my update interval to 2mins, and the screen stays at forecast theme, 30 mins past without reboot.

**Comment by 19201003080114** [comment] 2024-03-27 02:07
> Hi, what is your location? I have try set my update interval to 2mins, and the screen stays at forecast theme, 30 mins past without reboot.

Location is Toronto, Canada. 6167865

**Comment by GeekMagicClock** [comment] 2024-03-27 02:11
> > Hi, what is your location? I have try set my update interval to 2mins, and the screen stays at forecast theme, 30 mins past without reboot.
> 
> Location is Toronto, Canada. 6167865 Also happens for North York, Canada. 6091104

OK, have you set the auto switch between themes?

**Comment by GeekMagicClock** [comment] 2024-03-27 02:17
And yesterday I have updated two different v9.0.17, I doubt if you have update the earlier one, can you try the one now in the repo ?

**Comment by 19201003080114** [comment] 2024-03-27 02:22
> > > Hi, what is your location? I have try set my update interval to 2mins, and the screen stays at forecast theme, 30 mins past without reboot.
> > 
> > 
> > Location is Toronto, Canada. 6167865 Also happens for North York, Canada. 6091104
> 
> OK, have you set the auto switch between themes?

Yes I have auto switch themes on
<img width="399" alt="image" src="https://github.com/GeekMagicClock/smalltv-ultra/assets/158797249/ec821163-b687-43b5-8521-0c880d253857">

**Comment by 19201003080114** [comment] 2024-03-27 02:26
> And yesterday I have updated two different v9.0.17, I doubt if you have update the earlier one, can you try the one now in the repo ?

I just download V9.0.17 again. Is the MD5 cf8da165ca6c1a42bbd441b34a74cd9c?

**Comment by GeekMagicClock** [comment] 2024-03-27 02:33
Got it, since the ram is quite limited, maybe the auto switch theme caused the problem.
Yes, MD5 correct.

**Comment by GeekMagicClock** [comment] 2024-03-27 04:42
> > And yesterday I have updated two different v9.0.17, I doubt if you have update the earlier one, can you try the one now in the repo ?
> 
> I just download V9.0.17 again. Is the MD5 cf8da165ca6c1a42bbd441b34a74cd9c? I updated it just now and I will be monitoring it.

I can reproduce that, the loop between themes would randomly cause the reboot, I'm checking.

**Comment by angrycatmeowmeow** [comment] 2024-03-27 18:09
Can confirm seeing the same behavior. I only have two themes switching.  9.0.17.
![image](https://github.com/GeekMagicClock/smalltv-ultra/assets/67968528/99cd5153-ff03-4cf2-bf0d-dc15f35917b4)

**Comment by GeekMagicClock** [comment] 2024-03-28 00:48
@angrycatmeowmeow  @19201003080114  Please try the V9.0.18 version if that's convient for you, I have tested it for one night with the default interval of 20min without reboot, I'll test it with higher frequency and report here.

**Comment by 19201003080114** [comment] 2024-03-28 02:16
> @angrycatmeowmeow @19201003080114 Please try the V9.0.18 version if that's convient for you, I have tested it for one night with the default interval of 20min without reboot, I'll test it with higher frequency and report here.

I downloaded V9.0.18 and I am testing now.
Weather update interval shortest is 5 mins with own API key. If less than 5 mins, the value is not saved, and it will revert back to 5 mins (maybe it is a bug?)

**Comment by angrycatmeowmeow** [comment] 2024-03-28 22:20
> @angrycatmeowmeow @19201003080114 Please try the V9.0.18 version if that's convient for you, I have tested it for one night with the default interval of 20min without reboot, I'll test it with higher frequency and report here.

So far so good and the forecast screen Fahrenheit is fixed too. Thank you!

**Comment by 19201003080114** [comment] 2024-03-29 02:26
> > @angrycatmeowmeow @19201003080114 Please try the V9.0.18 version if that's convient for you, I have tested it for one night with the default interval of 20min without reboot, I'll test it with higher frequency and report here.
> 
> I downloaded V9.0.18 and I am testing now. Weather update interval shortest is 5 mins with own API key. If less than 5 mins, the value is not saved, and it will revert back to 5 mins (maybe it is a bug?)

I left V9.0.18 for about 12 hours now.
No signs of rebooting with the same auto theme rotation as V9.0.15, and with weather update interval of 5 mins. 
Forecast screen did not lose data (meaning no reboot within last 5 mins), and no random appearance of GIFTV screen that requires a manual restart.
I will keep monitoring. So far it is looking good.

**Comment by GeekMagicClock** [comment] 2024-03-31 08:31
Thank you guys for the report.

Updates: It may will not reboot, but I noticed sometimes the gif under the weather screen will not be displayed, but will be recover after several loops, that is because of not enough space ram.

And another thing about the update interval limit, I'll check that, if that is a bug, will be fixed in next updates.

**Closed** 2024-05-26 04:55 UTC
